#!/usr/bin/env bash
# Regenerate the committed mise pin: release checksums and the idiomatic
# version-file allowlist.
#
#   scripts/generate-mise-idiomatic.sh          # rewrite docker/mise/*
#   scripts/generate-mise-idiomatic.sh --check  # verify they match the pin (CI)
#
# Both artifacts are derived from the exact release named by MISE_VERSION in the
# Dockerfile, so a version bump is one edit here plus one run of this script:
#
#   - docker/mise/SHA256SUMS   the linux amd64/arm64 release checksums, verified
#                              by the Dockerfile before the binary is installed;
#   - docker/mise/config.toml  the system-wide mise policy installed at
#                              /etc/mise/config.toml, including the generated
#                              idiomatic allowlist.
#
# mise has no wildcard for idiomatic version-file detection, so the allowlist
# must be the exact set of tool IDs whose registry entries declare an
# `idiomatic_files` key. It is read from the release's own registry, not from
# whatever mise version happens to be on PATH.
set -euo pipefail

cd "$(dirname "$0")/.."

CHECK_ONLY=false
[ "${1:-}" = "--check" ] && CHECK_ONLY=true

DOCKERFILE=Dockerfile
CONFIG=docker/mise/config.toml
CHECKSUMS=docker/mise/SHA256SUMS

MISE_VERSION="$(grep -m1 '^ARG MISE_VERSION=' "$DOCKERFILE" | cut -d= -f2)"
if [ -z "$MISE_VERSION" ]; then
  echo "generate-mise-idiomatic.sh: no ARG MISE_VERSION in $DOCKERFILE" >&2
  exit 1
fi
REF="v${MISE_VERSION}"
RELEASE="https://github.com/jdx/mise/releases/download/${REF}"
SOURCE="https://github.com/jdx/mise/archive/refs/tags/${REF}.tar.gz"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# --- release checksums -------------------------------------------------------
# The upstream file lists every platform. Keep the two Linux architectures this
# image builds and record where they came from, so the committed hashes are
# auditable without the network.
curl -fsSL "${RELEASE}/SHASUMS256.txt" -o "$TMP/SHASUMS256.txt"
{
  printf '# mise %s release checksums for the architectures this image builds.\n' "$MISE_VERSION"
  printf '# @generated by scripts/generate-mise-idiomatic.sh - do not edit.\n'
  printf '# Source: %s/SHASUMS256.txt\n' "$RELEASE"
  awk -v want="mise-v${MISE_VERSION}-linux-x64 mise-v${MISE_VERSION}-linux-arm64" '
    { name = $2; sub(/^\.\//, "", name) }
    index(" " want " ", " " name " ") { print $1 "  " name }
  ' "$TMP/SHASUMS256.txt" | sort -k2
} > "$TMP/SHA256SUMS"

missing="$(for a in x64 arm64; do
  grep -q "mise-v${MISE_VERSION}-linux-${a}\$" "$TMP/SHA256SUMS" || echo "$a"
done)"
if [ -n "$missing" ]; then
  echo "generate-mise-idiomatic.sh: release ${REF} has no checksum for: ${missing}" >&2
  exit 1
fi

# --- idiomatic allowlist -----------------------------------------------------
# The source tarball carries the registry that was compiled into this release.
# A tool supports idiomatic version files when its registry entry declares them;
# `idiomatic_files` is always a top-level key, so a column-zero match is exact.
curl -fsSL "$SOURCE" -o "$TMP/mise-src.tar.gz"
mkdir -p "$TMP/src"
tar xzf "$TMP/mise-src.tar.gz" -C "$TMP/src"

SOURCE_ROOT="$(find "$TMP/src" -mindepth 1 -maxdepth 1 -type d -name 'mise-*' -print -quit)"
REGISTRY="${SOURCE_ROOT}/registry"
if [ -z "$SOURCE_ROOT" ] || [ ! -d "$REGISTRY" ]; then
  echo "generate-mise-idiomatic.sh: no top-level registry directory in ${REF} source" >&2
  exit 1
fi

shopt -s nullglob
registry_files=("$REGISTRY"/*.toml)
shopt -u nullglob
if [ "${#registry_files[@]}" -eq 0 ]; then
  echo "generate-mise-idiomatic.sh: no registry entries in ${REF} source" >&2
  exit 1
fi

TOOLS="$(grep -lE '^idiomatic_files[[:space:]]*=' "${registry_files[@]}" \
  | sed 's#.*/##; s#\.toml$##' | sort -u || true)"
if [ -z "$TOOLS" ]; then
  echo "generate-mise-idiomatic.sh: no idiomatic tools found in ${REF} registry" >&2
  exit 1
fi

{
  cat <<EOF
# @generated by scripts/generate-mise-idiomatic.sh for mise ${MISE_VERSION} - do not edit.
#
# System-wide mise policy, installed at /etc/mise/config.toml. This is the
# lowest-precedence config every user and every \`docker exec\` reads; personal
# (~/.config/mise/config.toml) and project (mise.toml) configs override it. It
# never points at user state, so root reads the same policy without gaining
# access to the t3 user's toolchains.
#
#   auto_install                 an explicit mise execution installs a declared,
#                                missing tool instead of using a system one.
#   not_found_system_fallback    ...and if it cannot install, it fails rather
#                                than silently running a tool from PATH. This
#                                only governs execution that reaches mise;
#                                direct PATH calls are outside the guarantee.
#   pin                          \`mise use\` records the resolved exact version
#                                instead of a floating selector, so an installed
#                                personal tool never updates on its own.
#   minimum_release_age          a release counts as the newest once it has been
#                                out for a day, so one pulled or compromised
#                                within hours of publishing is never picked for
#                                you. mise already waits this long by default;
#                                it is set here so the setup page can say so.
#                                Naming an exact version installs it at once.
#   idiomatic_version_file_enable_tools
#                                the exact allowlist of tools in this release's
#                                registry that declare an idiomatic version
#                                file. mise has no wildcard for this setting,
#                                so it is generated and must be refreshed with
#                                the script named above when MISE_VERSION moves.
[settings]
auto_install = true
not_found_system_fallback = false
pin = true
minimum_release_age = "24h"
idiomatic_version_file_enable_tools = [
EOF
  printf '%s\n' "$TOOLS" | sed 's/^/  "/; s/$/",/'
  printf ']\n'
} > "$TMP/config.toml"

# --- write or check ----------------------------------------------------------
status=0
check_file() {
  local generated="$1" committed="$2" label="$3"
  if [ ! -f "$committed" ]; then
    if [ "$CHECK_ONLY" = true ]; then
      echo "$label is missing" >&2
      status=1
    else
      install -D -m 0644 "$generated" "$committed"
      echo "wrote $label"
    fi
    return 0
  fi
  if diff -u "$committed" "$generated" > "$TMP/diff"; then
    if [ "$CHECK_ONLY" = true ]; then
      echo "$label is current for mise ${MISE_VERSION}"
    fi
    return 0
  fi
  if [ "$CHECK_ONLY" = true ]; then
    echo "$label is out of date with mise ${MISE_VERSION}:" >&2
    sed -n '1,80p' "$TMP/diff" >&2
    status=1
  else
    install -D -m 0644 "$generated" "$committed"
    echo "wrote $label"
  fi
}

check_file "$TMP/SHA256SUMS" "$CHECKSUMS" "$CHECKSUMS"
check_file "$TMP/config.toml" "$CONFIG" "$CONFIG"

exit "$status"
